### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by dijikul** [jdallal/Reddit-Web-Data-Connector#1]
I've cloned this and hosted it on a webserver but am faced with the following error when attempting to make use of this WDC:

TypeError: undefined is not an object (evaluating 'results[results.length - 1]['ID']') file: http://domain/redditConnector.html line: 92
Unable to create extract

**Comment by jdallal** [comment]
Should be fixed now.  Try again and open a new issue with your settings if you're still seeing this, please.  Thanks.
