### ISSUE TITLE
Bugs in connector prevent it from working with tableau wdc

### ISSUE THREAD

**Issue by extrospective** [jdallal/Reddit-Web-Data-Connector#2]
1. results count must be initialized to zero.  While it works in simulator, this is only because simulator is single phase. When actual tableau wdc runs its two phase and then the resultcount is NaN when doing the actual pull.  This results in an error where tableau never returns when doing a query
2. when querying > 100, the code for the lastID is incorrect as the prefix t3_ should not be added

(Several of us were trying to use this at the hackathon today and found these defects.)

**Comment by jdallal** [comment]
Should work up through 1000 results now.  Please post the error you're getting and settings (subreddit, sort order, etc.) if you still see the problem.  Thanks.
